### ISSUE TITLE
ModuleNotFoundError: No module named 'medcat.utils.config_utils' when trying to open custom document

### ISSUE THREAD

**Issue by LWserenic** [CogStack/MedCATtrainer#198]
Hello @tomolopolis, I want to run the MedCATtrainer after creating my own custom model following the procedure from the paper. I got to an issue where when I want to open any document I got greeted with an empty error
![image](https://github.com/user-attachments/assets/9570da7d-f546-481e-b1f8-20abd90ad8a7)

I don't know what did I do wrong because when opening the UMLS example it opens as usual. After checking the log from Docker Desktop I found a line mentioning the error just as the title said. I already try using a cleaned text data that remove any special characters and also the raw data and the result is the same. What should I do?

**Comment by LWserenic** [comment]
If needed here are the lines printed by the Docker Desktop

`2024-07-25 16:19:33 medcattrainer-1            | INFO 2024-07-25 09:19:33,458 serializer.py l:164:Reading CDB data from /home/api/media/cdb_zgdhHDo.dat
2024-07-25 16:19:34 medcattrainer-1            | Internal Server Error: /api/cache-model/4/
2024-07-25 16:19:34 medcattrainer-1            | Traceback (most recent call last):
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 34, in inner
2024-07-25 16:19:34 medcattrainer-1            |     response = get_response(request)
2024-07-25 16:19:34 medcattrainer-1            |                ^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 115, in _get_response
2024-07-25 16:19:34 medcattrainer-1            |     response = self.process_exception_by_middleware(e, request)
2024-07-25 16:19:34 medcattrainer-1            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 113, in _get_response
2024-07-25 16:19:34 medcattrainer-1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-07-25 16:19:34 medcattrainer-1            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2024-07-25 16:19:34 medcattrainer-1            |     return view_func(*args, **kwargs)
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 71, in view
2024-07-25 16:19:34 medcattrainer-1            |     return self.dispatch(request, *args, **kwargs)
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
2024-07-25 16:19:34 medcattrainer-1            |     response = self.handle_exception(exc)
2024-07-25 16:19:34 medcattrainer-1            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
2024-07-25 16:19:34 medcattrainer-1            |     self.raise_uncaught_exception(exc)
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2024-07-25 16:19:34 medcattrainer-1            |     raise exc
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
2024-07-25 16:19:34 medcattrainer-1            |     response = handler(request, *args, **kwargs)
2024-07-25 16:19:34 medcattrainer-1            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
2024-07-25 16:19:34 medcattrainer-1            |     return func(*args, **kwargs)
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/home/api/api/views.py", line 614, in cache_model
2024-07-25 16:19:34 medcattrainer-1            |     get_cached_cdb(cdb_id, CDB_MAP)
2024-07-25 16:19:34 medcattrainer-1            |   File "/home/api/api/utils.py", line 273, in get_cached_cdb
2024-07-25 16:19:34 medcattrainer-1            |     cdb = CDB.load(cdb_obj.cdb_file.path)
2024-07-25 16:19:34 medcattrainer-1            |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/medcat/cdb.py", line 570, in load
2024-07-25 16:19:34 medcattrainer-1            |     cdb = ser.deserialize(CDB)
2024-07-25 16:19:34 medcattrainer-1            |           ^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/medcat/utils/saving/serializer.py", line 166, in deserialize
2024-07-25 16:19:34 medcattrainer-1            |     data = dill.load(f)
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/dill/_dill.py", line 289, in load
2024-07-25 16:19:34 medcattrainer-1            |     return Unpickler(file, ignore=ignore, **kwds).load()
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/dill/_dill.py", line 444, in load
2024-07-25 16:19:34 medcattrainer-1            |     obj = StockUnpickler.load(self)
2024-07-25 16:19:34 medcattrainer-1            |           ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/dill/_dill.py", line 434, in find_class
2024-07-25 16:19:34 medcattrainer-1            |     return StockUnpickler.find_class(self, module, name)
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            | ModuleNotFoundError: No module named 'medcat.utils.config_utils'
2024-07-25 16:19:34 medcattrainer-1            | ERROR 2024-07-25 09:19:34,928 log.py l:222:Internal Server Error: /api/cache-model/4/
2024-07-25 16:19:34 medcattrainer-1            | Traceback (most recent call last):
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 34, in inner
2024-07-25 16:19:34 medcattrainer-1            |     response = get_response(request)
2024-07-25 16:19:34 medcattrainer-1            |                ^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 115, in _get_response
2024-07-25 16:19:34 medcattrainer-1            |     response = self.process_exception_by_middleware(e, request)
2024-07-25 16:19:34 medcattrainer-1            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 113, in _get_response
2024-07-25 16:19:34 medcattrainer-1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-07-25 16:19:34 medcattrainer-1            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2024-07-25 16:19:34 medcattrainer-1            |     return view_func(*args, **kwargs)
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 71, in view
2024-07-25 16:19:34 medcattrainer-1            |     return self.dispatch(request, *args, **kwargs)
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
2024-07-25 16:19:34 medcattrainer-1            |     response = self.handle_exception(exc)
2024-07-25 16:19:34 medcattrainer-1            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
2024-07-25 16:19:34 medcattrainer-1            |     self.raise_uncaught_exception(exc)
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2024-07-25 16:19:34 medcattrainer-1            |     raise exc
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
2024-07-25 16:19:34 medcattrainer-1            |     response = handler(request, *args, **kwargs)
2024-07-25 16:19:34 medcattrainer-1            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
2024-07-25 16:19:34 medcattrainer-1            |     return func(*args, **kwargs)
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/home/api/api/views.py", line 614, in cache_model
2024-07-25 16:19:34 medcattrainer-1            |     get_cached_cdb(cdb_id, CDB_MAP)
2024-07-25 16:19:34 medcattrainer-1            |   File "/home/api/api/utils.py", line 273, in get_cached_cdb
2024-07-25 16:19:34 medcattrainer-1            |     cdb = CDB.load(cdb_obj.cdb_file.path)
2024-07-25 16:19:34 medcattrainer-1            |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/medcat/cdb.py", line 570, in load
2024-07-25 16:19:34 medcattrainer-1            |     cdb = ser.deserialize(CDB)
2024-07-25 16:19:34 medcattrainer-1            |           ^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/medcat/utils/saving/serializer.py", line 166, in deserialize
2024-07-25 16:19:34 medcattrainer-1            |     data = dill.load(f)
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/dill/_dill.py", line 289, in load
2024-07-25 16:19:34 medcattrainer-1            |     return Unpickler(file, ignore=ignore, **kwds).load()
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/dill/_dill.py", line 444, in load
2024-07-25 16:19:34 medcattrainer-1            |     obj = StockUnpickler.load(self)
2024-07-25 16:19:34 medcattrainer-1            |           ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            |   File "/usr/local/lib/python3.11/site-packages/dill/_dill.py", line 434, in find_class
2024-07-25 16:19:34 medcattrainer-1            |     return StockUnpickler.find_class(self, module, name)
2024-07-25 16:19:34 medcattrainer-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25 16:19:34 medcattrainer-1            | ModuleNotFoundError: No module named 'medcat.utils.config_utils'
2024-07-25 16:19:34 medcattrainer-1            | [pid: 44|app: 0|req: 220/218] 172.18.0.3 () {58 vars in 1269 bytes} [Thu Jul 25 09:19:33 2024] GET /api/cache-model/4/ => generated 15156 bytes in 1474 msecs (HTTP/1.0 500) 3 headers in 131 bytes (1 switches on core 0)
2024-07-25 16:19:34 medcattrainer-1            | [pid: 44|app: 0|req: 221/219] 172.18.0.3 () {56 vars in 1221 bytes} [Thu Jul 25 09:19:34 2024] GET /favicon.ico => generated 649 bytes in 0 msecs (HTTP/1.0 200) 3 headers in 109 bytes (1 switches on core 0)`

**Comment by mart-r** [comment]
It looks to me like you've uploaded a faulty file to MedCATtrainer as the CDB.

Do note that the way MedCATtrainer works, you need to upload just the CDB (generally `cdb.dat`), not the entire model pack (generally a `*.zip` file).
The `cdb.dat` is in the unpacked folder.

If you did in fact upload the CDB, make sure it's not been corrupted. Download it and try loading it locally. It should produce the same (or similar) error locally.

**Comment by LWserenic** [comment]
Hello @mart-r , thank you for the answer. So far I uploaded the cdb.dat, vocab.dat, and the dataset if I remember correctly. What to do in case it is corrupted?

**Comment by mart-r** [comment]
Sorry - I was wrong 

> Hello @mart-r , thank you for the answer. So far I uploaded the cdb.dat, vocab.dat, and the dataset if I remember correctly. What to do in case it is corrupted?

Sorry, I edited my above message. I was wrong:
> No - I was wrong. The issue is that you've created your model with medcat==1.12.0 and MedCATtrainer currently runs medcat~=1.10.0. The model is not backwards compatible.

There's a pull request on MedCAT to transform the medcat 1.12 model into a format usable on medcat 1.10 and 1.11:
https://github.com/CogStack/MedCAT/pull/465
If you want to convert the model, you can use that, either install from the git commit or simply clone the branch.
And then you can use:
If you installed the package using the commit:
```
python -m medcat.utils.versioning allow-pre-1.12 <INPUT_MODEL_PATH> <OUTPUT_MODEL_PATH>
```
If you simply cloned the branch:
```
python /path/to/installation/medcat/utils/versioning.py allow-pre-1.12 <INPUT_MODEL_PATH> <OUTPUT_MODEL_PATH>
```

**Comment by LWserenic** [comment]
Okay @mart-r thank you for the answer. I will try it when I have time. I'll inform you if it worked

**Comment by LWserenic** [comment]
Hello @mart-r, I obtained this error
usage: versioning.py [-h] [--overwrite] [--silent] [--verbose] {fix-config} modelpack newpath
versioning.py: error: argument action: invalid choice: 'allow-pre-1.12' (choose from 'fix-config')

I just look into the versioning.py and apparently allow-pre-1.12 didn't exist there...

**Comment by LWserenic** [comment]
Oh never mind I found it already, sorry.

**Comment by LWserenic** [comment]
Okay it works now. Thank you for the assistance
