### ISSUE TITLE
No example annotation project or dataset upon installation. 

### ISSUE THREAD

**Issue by coltonflowers1** [CogStack/MedCATtrainer#42]
After following readme instructions for installation, no demo annotation project, nor any example datasets were installed. I receive the following message in the terminal after initial installation: 

```
medcattrainer    | Detected path traversal attempt in '/home/api/media/Example Dataset.csv
medcattrainer    | Bad Request: /api/create-dataset/
medcattrainer    | [pid: 129|app: 0|req: 9/9] 127.0.0.1 () {38 vars in 527 bytes} [Wed Jul  7 17:46:23 2021] POST /api/create-dataset/ => generated 15266 bytes in 343 msecs (HTTP/1.1 400) 3 headers in 121 bytes (1 switches on core 0)
medcattrainer    | Checking for default projects / datasets / CDBs / Vocabs
medcattrainer    | Found No Objects. Populating Example: Concept DB, Vocabulary, Dataset and Project...
medcattrainer    | Downloading example CDB...
medcattrainer    | Downloading example vocab...
medcattrainer    | Downloading example dataset
medcattrainer    | Creating CDB / Vocab / Dataset / Project in the Trainer
medcattrainer    | Traceback (most recent call last):
medcattrainer    |   File "/home/load_examples.py", line 72, in <module>
medcattrainer    |     ds_id = json.loads(resp.text)['dataset_id']
medcattrainer    |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
medcattrainer    |     return _default_decoder.decode(s)
medcattrainer    |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
medcattrainer    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
medcattrainer    |   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
medcattrainer    |     raise JSONDecodeError("Expecting value", s, err.value) from None
medcattrainer    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by tomolopolis** [comment]
Looks like the newly created dataset hasn't been created properly. I think our latest build, has this fixed. 

You should still be able to upload your own / or the example datasets manually via the django admin interface, i.e. http://<your-server-IP>/admin/
