### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATtrainer#47]
Hi @tomolopolis I found another issue with the current master branch and thought it would be best to create a separate issue for this.

When starting new containers (and new volumes) on the current master branch, I think the code that loads the demo data fails to connect to the API, and because of that the demo is not working:

```
 Checking for default projects / datasets / CDBs / Vocabs
medcattrainer_1  | Traceback (most recent call last):
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
medcattrainer_1  |     (self._dns_host, self.port), self.timeout, **extra_kw
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
medcattrainer_1  |     raise err
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
medcattrainer_1  |     sock.connect(sa)
medcattrainer_1  | ConnectionRefusedError: [Errno 111] Connection refused
medcattrainer_1  | 
medcattrainer_1  | During handling of the above exception, another exception occurred:
medcattrainer_1  | 
medcattrainer_1  | Traceback (most recent call last):
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
medcattrainer_1  |     chunked=chunked,
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
medcattrainer_1  |     conn.request(method, url, **httplib_request_kw)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request
medcattrainer_1  |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
medcattrainer_1  |   File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
medcattrainer_1  |     self._send_request(method, url, body, headers, encode_chunked)
medcattrainer_1  |   File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
medcattrainer_1  |     self.endheaders(body, encode_chunked=encode_chunked)
medcattrainer_1  |   File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
medcattrainer_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
medcattrainer_1  |   File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
medcattrainer_1  |     self.send(msg)
medcattrainer_1  |   File "/usr/local/lib/python3.7/http/client.py", line 972, in send
medcattrainer_1  |     self.connect()
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
medcattrainer_1  |     conn = self._new_conn()
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
medcattrainer_1  |     self, "Failed to establish a new connection: %s" % e
medcattrainer_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1f0af45c90>: Failed to establish a new connection: [Errno 111] Connection refused
medcattrainer_1  | 
medcattrainer_1  | During handling of the above exception, another exception occurred:
medcattrainer_1  | 
medcattrainer_1  | Traceback (most recent call last):
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
medcattrainer_1  |     timeout=timeout
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
medcattrainer_1  |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
medcattrainer_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
medcattrainer_1  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f0af45c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
medcattrainer_1  | 
medcattrainer_1  | During handling of the above exception, another exception occurred:
medcattrainer_1  | 
medcattrainer_1  | Traceback (most recent call last):
medcattrainer_1  |   File "/home/load_examples.py", line 107, in <module>
medcattrainer_1  |     main()
medcattrainer_1  |   File "/home/load_examples.py", line 20, in main
medcattrainer_1  |     if requests.get(URL).status_code == 200:
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
medcattrainer_1  |     return request('get', url, params=params, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
medcattrainer_1  |     return session.request(method=method, url=url, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
medcattrainer_1  |     resp = self.send(prep, **send_kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
medcattrainer_1  |     r = adapter.send(request, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
medcattrainer_1  |     raise ConnectionError(e, request=request)
medcattrainer_1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f0af45c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
medcattrainer_1  | Unauthorized: /api/project-annotate-entities
```

**Comment by tomolopolis** [comment]
Hi @sandertan - thanks for flagging, have fixed [here](https://github.com/CogStack/MedCATtrainer/commit/edb8f72e806307058a84fae5e64b8af42e3cb31c)

**Comment by sandertan** [comment]
@tomolopolis Thanks for fixing that one. I'm getting a new error after pulling and rebuilding (`docker-compose -f docker-compose-dev.yml build`) on startup and when clicking "Demo":
```
medcattrainer_1  | [pid: 95|app: 0|req: 14/14] 172.28.0.3 () {56 vars in 1190 bytes} [Mon Sep 27 10:24:10 2021] GET /api/project-annotate-entities/ => generated 52 bytes in 18 msecs (HTTP/1.0 200) 5 headers in 147 bytes (1 switches on core 0)
medcattrainer_1  | Internal Server Error: /api/complete-projects/
medcattrainer_1  | Traceback (most recent call last):
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
medcattrainer_1  |     response = get_response(request)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
medcattrainer_1  |     response = self.process_exception_by_middleware(e, request)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
medcattrainer_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
medcattrainer_1  |     return view_func(*args, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
medcattrainer_1  |     return self.dispatch(request, *args, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
medcattrainer_1  |     response = self.handle_exception(exc)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
medcattrainer_1  |     self.raise_uncaught_exception(exc)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
medcattrainer_1  |     raise exc
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
medcattrainer_1  |     response = handler(request, *args, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/decorators.py", line 50, in handler
medcattrainer_1  |     return func(*args, **kwargs)
medcattrainer_1  |   File "./api/views.py", line 533, in finished_projects
medcattrainer_1  |     projects = ProjectAnnotateEntities.objects.filter(id__in=project_ids.split(','))
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
medcattrainer_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 892, in filter
medcattrainer_1  |     return self._filter_or_exclude(False, *args, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/polymorphic/query.py", line 187, in _filter_or_exclude
medcattrainer_1  |     negate, *(list(q_objects) + additional_args), **kwargs
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
medcattrainer_1  |     clone.query.add_q(Q(*args, **kwargs))
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1290, in add_q
medcattrainer_1  |     clause, _ = self._add_q(q_object, self.used_aliases)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
medcattrainer_1  |     split_subq=split_subq, simple_col=simple_col,
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
medcattrainer_1  |     condition = self.build_lookup(lookups, col, value)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1116, in build_lookup
medcattrainer_1  |     lookup = lookup_class(lhs, rhs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/lookups.py", line 20, in __init__
medcattrainer_1  |     self.rhs = self.get_prep_lookup()
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/lookups.py", line 210, in get_prep_lookup
medcattrainer_1  |     rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 972, in get_prep_value
medcattrainer_1  |     return int(value)
medcattrainer_1  | ValueError: invalid literal for int() with base 10: '
nginx_1          | 172.28.0.1 - - [27/Sep/2021:10:24:10 +0000] "GET /api/complete-projects/?projects= HTTP/1.1" 500 15500 "http://localhost:8001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36"
medcattrainer_1  | [pid: 95|app: 0|req: 15/15] 172.28.0.3 () {56 vars in 1193 bytes} [Mon Sep 27 10:24:10 2021] GET /api/complete-projects/?projects= => generated 15500 bytes in 140 msecs (HTTP/1.0 500) 3 headers in 131 bytes (1 switches on core 0)
medcattrainer_1  | [pid: 95|app: 0|req: 16/16] 172.28.0.3 () {56 vars in 1194 bytes} [Mon Sep 27 10:24:36 2021] GET /api/project-annotate-entities/ => generated 52 bytes in 14 msecs (HTTP/1.0 200) 5 headers in 147 bytes (1 switches on core 0)
nginx_1          | 172.28.0.1 - - [27/Sep/2021:10:24:36 +0000] "GET /api/project-annotate-entities/ HTTP/1.1" 200 52 "http://localhost:8001/demo" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36"
medcattrainer_1  | [pid: 95|app: 0|req: 17/17] 172.28.0.3 () {54 vars in 1122 bytes} [Mon Sep 27 10:24:36 2021] GET /favicon.ico => generated 962 bytes in 2 msecs (HTTP/1.0 200) 3 headers in 109 bytes (1 switches on core 0)
nginx_1          | 172.28.0.1 - - [27/Sep/2021:10:24:36 +0000] "GET /favicon.ico HTTP/1.1" 200 447 "http://localhost:8001/demo" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36"
medcattrainer_1  | [pid: 95|app: 0|req: 18/18] 127.0.0.1 () {38 vars in 577 bytes} [Mon Sep 27 10:25:18 2021] POST /api/concept-dbs/ => generated 105 bytes in 7033 msecs (HTTP/1.1 201) 5 headers in 144 bytes (8582 switches on core 0)
medcattrainer_1  | [pid: 95|app: 0|req: 19/19] 127.0.0.1 () {38 vars in 567 bytes} [Mon Sep 27 10:25:25 2021] POST /api/vocabs/ => generated 61 bytes in 5466 msecs (HTTP/1.1 201) 5 headers in 143 bytes (6588 switches on core 0)
medcattrainer_1  | Internal Server Error: /api/create-dataset/
medcattrainer_1  | Traceback (most recent call last):
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
medcattrainer_1  |     response = get_response(request)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
medcattrainer_1  |     response = self.process_exception_by_middleware(e, request)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
medcattrainer_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
medcattrainer_1  |     return view_func(*args, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
medcattrainer_1  |     return self.dispatch(request, *args, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
medcattrainer_1  |     response = self.handle_exception(exc)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
medcattrainer_1  |     self.raise_uncaught_exception(exc)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
medcattrainer_1  |     raise exc
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
medcattrainer_1  |     response = handler(request, *args, **kwargs)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/decorators.py", line 50, in handler
medcattrainer_1  |     return func(*args, **kwargs)
medcattrainer_1  |   File "./api/views.py", line 516, in create_dataset
medcattrainer_1  |     pd.DataFrame(request.data['dataset']).to_csv(filename, index=False)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 614, in __init__
medcattrainer_1  |     mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 465, in dict_to_mgr
medcattrainer_1  |     arrays, data_names, index, columns, dtype=dtype, typ=typ, consolidate=copy
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
medcattrainer_1  |     index = _extract_index(arrays)
medcattrainer_1  |   File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 625, in _extract_index
medcattrainer_1  |     raise ValueError("If using all scalar values, you must pass an index")
medcattrainer_1  | ValueError: If using all scalar values, you must pass an index
medcattrainer_1  | [pid: 95|app: 0|req: 20/20] 127.0.0.1 () {38 vars in 533 bytes} [Mon Sep 27 10:25:31 2021] POST /api/create-dataset/ => generated 13560 bytes in 48 msecs (HTTP/1.1 500) 3 headers in 131 bytes (1 switches on core 0)
medcattrainer_1  | Checking for default projects / datasets / CDBs / Vocabs
medcattrainer_1  | Found No Objects. Populating Example: Concept DB, Vocabulary, Dataset and Project...
medcattrainer_1  | Downloading example CDB...
medcattrainer_1  | Downloading example vocab...
medcattrainer_1  | Downloading example dataset
medcattrainer_1  | Creating CDB / Vocab / Dataset / Project in the Trainer
medcattrainer_1  | Traceback (most recent call last):
medcattrainer_1  |   File "/home/load_examples.py", line 107, in <module>
medcattrainer_1  |     main()
medcattrainer_1  |   File "/home/load_examples.py", line 56, in main
medcattrainer_1  |     create_example_project(URL, headers, cdb_tmp_file, vocab_tmp_file, ds_dict)
medcattrainer_1  |   File "/home/load_examples.py", line 87, in create_example_project
medcattrainer_1  |     ds_id = json.loads(resp.text)['dataset_id']
medcattrainer_1  |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
medcattrainer_1  |     return _default_decoder.decode(s)
medcattrainer_1  |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
medcattrainer_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
medcattrainer_1  |   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
medcattrainer_1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
medcattrainer_1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
