### ISSUE TITLE
Concept Lookup error in search_solr in MCT 2.2.7

### ISSUE THREAD

**Issue by arfenarf** [CogStack/MedCATtrainer#81]
Thank you for looking at better ways to index concepts: I've successfully imported concepts into Apache Solr (so fast!) but when I try to look up a concept in the tagging GUI, MedCat Trainer throws the error below: any ideas why?

```
Internal Server Error: /api/search-concepts/
2022-05-21T20:40:46.595648573Z Traceback (most recent call last):
2022-05-21T20:40:46.595654925Z   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2022-05-21T20:40:46.595659133Z     response = get_response(request)
2022-05-21T20:40:46.595662870Z   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
2022-05-21T20:40:46.595667038Z     response = self.process_exception_by_middleware(e, request)
2022-05-21T20:40:46.595671016Z   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
2022-05-21T20:40:46.595694159Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2022-05-21T20:40:46.595698297Z   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2022-05-21T20:40:46.595701844Z     return view_func(*args, **kwargs)
2022-05-21T20:40:46.595705030Z   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
2022-05-21T20:40:46.595708406Z     return self.dispatch(request, *args, **kwargs)
2022-05-21T20:40:46.595711642Z   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
2022-05-21T20:40:46.595715159Z     response = self.handle_exception(exc)
2022-05-21T20:40:46.595718676Z   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
2022-05-21T20:40:46.595723094Z     self.raise_uncaught_exception(exc)
2022-05-21T20:40:46.595726430Z   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2022-05-21T20:40:46.595729887Z     raise exc
2022-05-21T20:40:46.595733013Z   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
2022-05-21T20:40:46.595736329Z     response = handler(request, *args, **kwargs)
2022-05-21T20:40:46.595739515Z   File "/usr/local/lib/python3.7/site-packages/rest_framework/decorators.py", line 50, in handler
2022-05-21T20:40:46.595742871Z     return func(*args, **kwargs)
2022-05-21T20:40:46.595746248Z   File "./api/views.py", line 651, in search_solr
2022-05-21T20:40:46.595750165Z     cdbs = request.GET.get('cdbs').split(',')
2022-05-21T20:40:46.595754173Z AttributeError: 'NoneType' object has no attribute 'split'
2022-05-21T20:40:46.595757489Z ERROR 2022-05-21 20:40:46,595 log.py l:228:Internal Server Error: /api/search-concepts/
2022-05-21T20:40:46.595760725Z Traceback (most recent call last):
2022-05-21T20:40:46.595764142Z   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2022-05-21T20:40:46.595768159Z     response = get_response(request)
2022-05-21T20:40:46.595773169Z   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
2022-05-21T20:40:46.595780473Z     response = self.process_exception_by_middleware(e, request)
2022-05-21T20:40:46.595783849Z   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
2022-05-21T20:40:46.595787165Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2022-05-21T20:40:46.595790381Z   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2022-05-21T20:40:46.595793738Z     return view_func(*args, **kwargs)
2022-05-21T20:40:46.595796864Z   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
2022-05-21T20:40:46.595804027Z     return self.dispatch(request, *args, **kwargs)
2022-05-21T20:40:46.595807484Z   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
2022-05-21T20:40:46.595810940Z     response = self.handle_exception(exc)
2022-05-21T20:40:46.595814206Z   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
2022-05-21T20:40:46.595817543Z     self.raise_uncaught_exception(exc)
2022-05-21T20:40:46.595820699Z   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2022-05-21T20:40:46.595824055Z     raise exc
2022-05-21T20:40:46.595827151Z   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
2022-05-21T20:40:46.595830477Z     response = handler(request, *args, **kwargs)
2022-05-21T20:40:46.595833653Z   File "/usr/local/lib/python3.7/site-packages/rest_framework/decorators.py", line 50, in handler
2022-05-21T20:40:46.595837350Z     return func(*args, **kwargs)
2022-05-21T20:40:46.595841388Z   File "./api/views.py", line 651, in search_solr
2022-05-21T20:40:46.595844614Z     cdbs = request.GET.get('cdbs').split(',')
2022-05-21T20:40:46.595847780Z AttributeError: 'NoneType' object has no attribute 'split'
2022-05-21T20:40:46.596297751Z [pid: 842|app: 0|req: 480/480] 172.20.0.4 () {56 vars in 1473 bytes} [Sat May 21 20:40:46 2022] GET /api/search-concepts/?search=bad\scirculation&cdb__in=2 => generated 14655 bytes in 16 msecs (HTTP/1.0 500) 3 headers in 131 bytes (1 switches on core 0)
```

**Comment by arfenarf** [comment]
Amending `search_solr()` thus makes the error go away, although search results are a little peculiar if they appear at all:

```
def search_solr(request):
    query = request.GET.get('search')
    # cdbs = request.GET.get('cdbs').split(',')
    cdbs = request.GET.get('cdb__in').split(',')
    return search_collection(cdbs, query)
```

**Comment by tomolopolis** [comment]
Hi @arfenarf - this new feature hadn't released yet. I've just kicked off the 2.3.0 release and updated the docker-compose.yml so in a hour or if you git pull the changes will work. 

For reference - to pull in the latest changes on master and actually use them you'll need to use 

`$ docker-compose -f docker-compose-dev.yml up`   to build and run bleeding edge features of MCT.
